[build]
builder = "nixpacks"
buildCommand = "npx prisma generate && npm run build"

[deploy]
startCommand = "npx prisma db push --skip-generate && npm start"
healthcheckPath = "/api/v1/openapi.json"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3

[[volumes]]
mount = "/data"
name = "sqlite-data"
